# Generated by Django 4.2.5 on 2025-05-08 18:37

from django.db import migrations, models
import django.db.models.deletion
import django_enum.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('name', models.TextField(max_length=4095)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.TextField(max_length=4095)),
                ('floor', models.TextField(max_length=4095)),
                ('entrance', models.TextField(max_length=4095)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(max_length=4095)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.TextField(max_length=4095)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField(max_length=4095)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('name', models.TextField(max_length=4095)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pay_period', django_enum.fields.EnumCharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('month', 'Month'), ("<class 'provider_app.models.TarifPayPeriod.Meta'>", 'Meta')], default='month', max_length=49)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tarif',
            constraint=models.CheckConstraint(check=models.Q(('pay_period__in', ['second', 'minute', 'hour', 'day', 'month', "<class 'provider_app.models.TarifPayPeriod.Meta'>"])), name='provider_app_Tarif_pay_period_TarifPayPeriod'),
        ),
        migrations.AddField(
            model_name='street',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='provider_app.city'),
        ),
        migrations.AddField(
            model_name='home',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='provider_app.city'),
        ),
        migrations.AddField(
            model_name='home',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='provider_app.street'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='provider_app.city'),
        ),
        migrations.AddField(
            model_name='address',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='provider_app.home'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='provider_app.street'),
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='provider_app.address'),
        ),
        migrations.AddField(
            model_name='account',
            name='tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarif', to='provider_app.tarif'),
        ),
        migrations.AddField(
            model_name='account',
            name='tarif_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarif_plan', to='provider_app.tarif'),
        ),
    ]
