# Generated by Django 5.1 on 2024-11-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=32768)),
                ('price', models.IntegerField()),
                ('period', models.CharField(max_length=256)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
