# Generated by Django 5.1 on 2024-11-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_firewallrestrictions_firewall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='period',
            field=models.CharField(choices=[('SECONDS', 'seconds'), ('MINUTES', 'minutes'), ('HOURS', 'hours'), ('DAYS', 'days'), ('WEEKS', 'weeks'), ('MONTHS', 'months'), ('YEARS', 'years')], default='MONTHS', max_length=256),
        ),
    ]
