# Generated by Django 5.1 on 2024-11-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_tarif_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirewallRestrictions',
        ),
    ]
