# Generated by Django 5.1 on 2024-11-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_firewallrestrictions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewallrestrictions',
            name='Firewall',
        ),
        migrations.DeleteModel(
            name='Firewall',
        ),
        migrations.DeleteModel(
            name='FirewallRestrictions',
        ),
    ]
