# Generated by Django 5.1 on 2024-11-09 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_remove_firewallrestrictions_firewall_delete_firewall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firewall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=32768)),
                ('tarif', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='server.tarif')),
            ],
        ),
        migrations.CreateModel(
            name='FirewallRestrictions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=32768)),
                ('ip_type', models.CharField(choices=[('IP', 'ip'), ('NET', 'net')], default='IP', max_length=256)),
                ('ip_area', models.CharField(choices=[('IP4', 'ip4'), ('IP6', 'ip6')], default='IP4', max_length=1024)),
                ('ip', models.CharField(max_length=256)),
                ('firewall', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='server.firewall')),
            ],
        ),
    ]
