# Generated by Django 5.1 on 2024-11-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_firewall_firewallrestrictions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirewallRestrictions',
            new_name='FirewallRestriction',
        ),
    ]
