# Generated by Django 5.1 on 2024-11-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_rename_firewallrestrictions_firewallrestriction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewall',
            name='tarif',
        ),
        migrations.RemoveField(
            model_name='firewallrestriction',
            name='firewall',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Tarif',
        ),
        migrations.DeleteModel(
            name='Firewall',
        ),
        migrations.DeleteModel(
            name='FirewallRestriction',
        ),
    ]
