# Generated by Django 5.1 on 2024-11-09 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0011_remove_firewall_tarif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firewall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=32768)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=32768)),
                ('price', models.IntegerField()),
                ('period', models.CharField(choices=[('SECONDS', 'seconds'), ('MINUTES', 'minutes'), ('HOURS', 'hours'), ('DAYS', 'days'), ('WEEKS', 'weeks'), ('MONTHS', 'months'), ('YEARS', 'years')], default='MONTHS', max_length=256)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FirewallRestriction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=32768)),
                ('ip_type', models.CharField(choices=[('IP', 'ip'), ('NET', 'net')], default='IP', max_length=256)),
                ('ip_area', models.CharField(choices=[('IP4', 'ip4'), ('IP6', 'ip6')], default='IP4', max_length=1024)),
                ('ip', models.CharField(max_length=256)),
                ('firewall', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='server.firewall')),
            ],
        ),
        migrations.AddField(
            model_name='firewall',
            name='tarif',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='server.tarif'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('tarif', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='server.tarif')),
            ],
        ),
    ]
